version: "3.5"

services:
  i2p:
    build:
      context: .
      # args:
      # context: docker/esi-cloud-gohan-devel
      # args:
      #   - GOVERSION=${GOVERSION:-1.10.1}
    container_name: i2p
    hostname: i2p
    image: mateumann/i2p
    deploy:
      mode: global
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      # - i2p:/i2p
      - home:/home/i2p
    networks:
      - i2p
    expose:
      - 4444
      - 4445
      - 7657
    ports:
      - 127.0.0.1:4444:4444
      - 127.0.0.1:4445:4445
      - 127.0.0.1:7657:7657

networks:
  i2p:
    # Use a custom driver
    # driver: custom-driver-1
    name: i2p

volumes:
  # i2p:
  home:
