version: '3.5'

services:
  i2p:
    build:
      context: .
      # args:
      # context: docker/esi-cloud-gohan-devel
      # args:
      #   - GOVERSION=${GOVERSION:-1.10.1}
    container_name: i2p
    image: mateumann/i2p
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    # volumes:
    #   - tor:/var/lib/tor
    #   - squid:/var/cache/squid
    networks:
      - i2p
    expose:
      - 7651
      - 7652
    ports:
      - 127.0.0.1:7651:7651
      - 127.0.0.1:7652:7652

networks:
  i2p:
    # Use a custom driver
    # driver: custom-driver-1
    name: i2p

# volumes:
#  tor:
#  squid:
