#!/usr/bin/expect -f
spawn java -jar /tmp/i2pinstall_0.9.43.jar -console
expect "Input selection:"
send -- "0\r"
expect "Press 1 to continue, 2 to quit, 3 to redisplay"
send -- "1\r"
expect "Press 1 to continue, 2 to quit, 3 to redisplay"
send -- "1\r"
expect "Select the installation path"
send -- "/i2p\r"
expect "Enter O for OK, C to Cancel:"
send -- "O\r"
expect "Press 1 to continue, 2 to quit, 3 to redisplay"
send -- "1\r"
expect "Press 1 to continue, 2 to quit, 3 to redisplay"
send -- "1\r"
expect "#"
